### PR TITLE
use Go native SQLite driver

### PR DESCRIPTION
**Pull request by vroldanbet**
This PR replaces github.com/mattn/go-sqlite3, which relies on `CGO`, with modernc.org/sqlite, a Go native implementation.

Using CGO adds extra friction in certain build pipelines, in particular those using language-specific build frameworks like https://github.com/ko-build/ko (see https://ko.build/advanced/limitations/)

The change was mostly a drop-in replacement, except I had to add the `MaxDBConn` limit to address SQLite single-writer ~limitation~ design choice. This shouldn't be too controversial, except I don't have an explanation to why the original implementation didn't need it.

### CODE REVIEW

**Comment by cschleiden** [comment]
!bench

**Review by cschleiden — APPROVED** [review]
LGTM! Thanks for this change

**Comment by cschleiden** [comment]
@vroldanbet Any idea if the time increase comes the connection limit or general perf difference in the two sqlite libraries? Looked at the non-CGO one and while it's supposed to be ~16% slower this here is a bit more.

**Comment by vroldanbet** [comment]
Hey @cschleiden! Thanks for looking into this 🙏🏻 

I'm not able to reproduce those numbers locally, and in fact the Go native implementation seems to be faster. Running those tests on an M2-Max.

````bash
# running main
hyperfine --warmup 1 -m 20 'go run .  -runs 2 -backend sqlite'
Benchmark 1: go run .  -runs 2 -backend sqlite
  Time (mean ± σ):      1.815 s ±  0.263 s    [User: 0.616 s, System: 0.511 s]
  Range (min … max):    1.447 s …  2.282 s    20 runs

# running with a commit before https://github.com/cschleiden/go-workflows/pull/239
hyperfine --warmup 1 -m 20 'go run .  -runs 2 -backend sqlite'
Benchmark 1: go run .  -runs 2 -backend sqlite
  Time (mean ± σ):     836.2 ms ±  73.4 ms    [User: 755.5 ms, System: 496.0 ms]
  Range (min … max):   699.3 ms … 976.8 ms    20 runs

# running with this PR 
vroldanbet@vrb-mbp bench % hyperfine --warmup 1 -m 20 'go run .  -runs 2 -backend sqlite'
Benchmark 1: go run .  -runs 2 -backend sqlite
  Time (mean ± σ):     640.9 ms ±  20.9 ms    [User: 549.9 ms, System: 443.8 ms]
  Range (min … max):   592.3 ms … 675.2 ms    20 runs
```

It would seem like the poll interval significantly regressed the performance, which I guess is by design. The [monoprocess PR](https://github.com/cschleiden/go-workflows/pull/240) may be a more sensible default

**Comment by cschleiden** [comment]
!bench

**Comment by cschleiden** [comment]
@vroldanbet good point about the polling interval. Merged master into the branch and benchmark looks good now. Going to merge once CI is green again! 🚀

**Comment by vroldanbet** [comment]
Thanks for the quick turnaround @cschleiden! 💯 ❤️

**Pull request merged**
